import Head from 'next/head'
import { Main } from 'templates'
import { Header, HighscoresGrid } from 'modules/Statistics'

export default function Statistics(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Exevo Pan - Highscores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <main>
          <Header />
          <HighscoresGrid />
        </main>
      </Main>
    </div>
  )
}
