export const routes = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: {
    ROOT: '/dashboard',
    TRANSACTIONS: '/dashboard/transaction-history',
    AUCTION_NOTIFICATIONS: '/dashboard/auction-notifications',
    DEVICES: '/dashboard/devices',
    REFERRALS: '/dashboard/referrals',
  },
  BOSSES: {
    TRACKER: '/bosses',
    HUNTING_GROUPS: '/bosses/hunting-groups',
  },
  ADVERTISE: '/highlight-auction',
  CALCULATORS: '/calculators',
  EXERCISE_WEAPONS: '/calculators/exercise-weapons',
  IMBUEMENTS_COST: '/calculators/imbuements-cost',
  CHARM_DAMAGE: '/calculators/charm-damage',
  STAMINA: '/calculators/stamina',
  LOOT_SPLIT: '/calculators/loot-split',
  AUCTION_ESTIMATION: '/calculators/auction-estimations',
  STATISTICS: '/statistics',
  HIGHSCORES: '/statistics/highscores',
  LIBERTABRA_WAR: '/libertabra-war',
  LIBERTABRA_WAR_TOP_10: '/libertabra-war/top-10',
  LIBERTABRA_WAR_GUILD_XP: '/libertabra-war/guild-xp',
  LIBERTABRA_WAR_SEARCH: '/libertabra-war/search',
  ABOUT: '/blog/about',
  BLOG: '/blog',
  EXEVOPRO: '/exevo-pro',
  ADMIN: {
    PRO_PAYMENTS: '/admin',
    AUCTION_HIGHLIGHTS: '/admin/auction-highlights',
    WITHDRAWS: '/admin/withdraws',
  },
}
