export const routes = {
  HOME: '/',
  BAZAAR_HISTORY: '/bazaar-history',
  ADVERTISE: '/highlight-auction',
  CALCULATORS: '/calculators',
  EXERCISE_WEAPONS: '/calculators/exercise-weapons',
  CHARM_DAMAGE: '/calculators/charm-damage',
  STATISTICS: '/statistics',
  HIGHSCORES: '/statistics/highscores',
  LIBERTABRA_WAR: '/libertabra-war',
  LIBERTABRA_WAR_TOP_10: '/libertabra-war/top-10',
  LIBERTABRA_WAR_GUILD_XP: '/libertabra-war/guild-xp',
  LIBERTABRA_WAR_SEARCH: '/libertabra-war/search',
  ABOUT: '/blog/about',
  BLOG: '/blog',
}
