declare interface FilterOptions {
  auctionIds: Set<number>
  nicknameFilter: string
  vocation: Set<number>
  pvp: Set<number>
  battleye: Set<boolean>
  location: Set<number>
  serverSet: Set<string>
  minLevel: number
  maxLevel: number
  minSkill: number
  maxSkill: number
  bossPoints: number
  minCharmPoints: number
  maxCharmPoints: number
  tcInvested: number
  tags: Set<string>
  skillKey: Set<string>
  imbuementsSet: Set<string>
  charmsSet: Set<string>
  rareNick: boolean
  questSet: Set<string>
  addon: number
  sex: boolean
  outfitSet: Set<string>
  storeOutfitSet: Set<string>
  mountSet: Set<string>
  storeMountSet: Set<string>
  achievementSet: Set<string>
  charmExpansion: boolean
  preySlot: boolean
  huntingSlot: boolean
  rewardShrine: boolean
  imbuementShrine: boolean
  dummy: boolean
  mailbox: boolean
  goldPouch: boolean
  hireling: boolean
  transferAvailable: boolean
  biddedOnly: boolean
}
