import { buildCharacterData } from '../utils'

export const charBuildedData = [
  {
    id: 546494,
    nickname: 'Delageez Shelby',
    auctionEnd: 1626487200,
    currentBid: 10000,
    hasBeenBidded: true,
    outfitId: '1243_3',
    serverId: 0,
    vocationId: 1,
    level: 618,
    skills: {
      magic: 11.79,
      club: 38.84,
      fist: 21.62,
      sword: 42.97,
      fishing: 43.63,
      axe: 119.13,
      distance: 23.35,
      shielding: 112.49,
    },
    items: [9079, 31577, 31633, 32616],
    charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 548069,
    nickname: 'Ganluca',
    auctionEnd: 1626487200,
    currentBid: 5011,
    hasBeenBidded: true,
    outfitId: '146_3',
    serverId: 1,
    vocationId: 1,
    level: 502,
    skills: {
      magic: 11.09,
      club: 44.25,
      fist: 14.15,
      sword: 55.19,
      fishing: 10.15,
      axe: 114.66,
      distance: 26.95,
      shielding: 107.27,
    },
    items: [16110, 16161, 21892, 31633],
    charms: ['Dodge', 'Freeze', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 550233,
    nickname: 'Stonurath Thel',
    auctionEnd: 1626487200,
    currentBid: 253,
    hasBeenBidded: true,
    outfitId: '131_0',
    serverId: 2,
    vocationId: 1,
    level: 8,
    skills: {
      magic: 2.35,
      club: 101.06,
      fist: 10,
      sword: 14,
      fishing: 10,
      axe: 14,
      distance: 13.64,
      shielding: 93.79,
    },
    items: [],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 550374,
    nickname: 'Old Riccs',
    auctionEnd: 1626487200,
    currentBid: 4000,
    hasBeenBidded: false,
    outfitId: '1243_2',
    serverId: 3,
    vocationId: 2,
    level: 450,
    skills: {
      magic: 32.42,
      club: 30.3,
      fist: 20.13,
      sword: 33.91,
      fishing: 13.46,
      axe: 13.55,
      distance: 118.81,
      shielding: 107.45,
    },
    items: [13994, 21383, 31633, 32630],
    charms: ['Dodge', 'Freeze'],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Paralize Removal',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 550520,
    nickname: 'Muscaria Cubensis',
    auctionEnd: 1626487200,
    currentBid: 300,
    hasBeenBidded: true,
    outfitId: '278_3',
    serverId: 4,
    vocationId: 2,
    level: 103,
    skills: {
      magic: 19.39,
      club: 13.82,
      fist: 11.18,
      sword: 13.82,
      fishing: 10,
      axe: 13.82,
      distance: 106.54,
      shielding: 96.04,
    },
    items: [7368, 7438, 7642, 16141],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 550716,
    nickname: 'Audax Insane',
    auctionEnd: 1626487200,
    currentBid: 10500,
    hasBeenBidded: false,
    outfitId: '152_2',
    serverId: 5,
    vocationId: 2,
    level: 570,
    skills: {
      magic: 34.07,
      club: 20.72,
      fist: 25.43,
      sword: 31.43,
      fishing: 10.75,
      axe: 26.27,
      distance: 119.09,
      shielding: 104.97,
    },
    items: [28493, 29417, 29428, 31633],
    charms: [
      'Curse',
      'Dodge',
      'Freeze',
      'Low Blow',
      'Parry',
      'Poison',
      'Wound',
      'Zap',
    ],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Paralize Removal',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 551186,
    nickname: 'Lued',
    auctionEnd: 1626487200,
    currentBid: 8000,
    hasBeenBidded: false,
    outfitId: '962_0',
    serverId: 6,
    vocationId: 1,
    level: 421,
    skills: {
      magic: 11.03,
      club: 13.67,
      fist: 12.6,
      sword: 102.1,
      fishing: 10,
      axe: 13.67,
      distance: 13.17,
      shielding: 97.16,
    },
    items: [27650, 28719, 28723, 32617],
    charms: ['Dodge', 'Freeze', 'Poison', 'Wound', 'Zap'],
    transfer: true,
    imbuements: [
      'Capacity',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
    ],
    hasSoulwar: false,
  },
  {
    id: 551395,
    nickname: 'Agora Tenho Cabelo',
    auctionEnd: 1626487200,
    currentBid: 57,
    hasBeenBidded: true,
    outfitId: '134_0',
    serverId: 7,
    vocationId: 3,
    level: 38,
    skills: {
      magic: 56.11,
      club: 12.66,
      fist: 10.96,
      sword: 13.74,
      fishing: 10,
      axe: 13.08,
      distance: 18.68,
      shielding: 31.31,
    },
    items: [3035, 3071, 3434, 8042],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 551614,
    nickname: 'Paje do morcego',
    auctionEnd: 1626487200,
    currentBid: 3000,
    hasBeenBidded: false,
    outfitId: '155_3',
    serverId: 0,
    vocationId: 4,
    level: 426,
    skills: {
      magic: 96.85,
      club: 13.53,
      fist: 17.39,
      sword: 17.42,
      fishing: 18.95,
      axe: 19.12,
      distance: 22.19,
      shielding: 35,
    },
    items: [6432, 29418, 31306, 31578],
    charms: ['Adrenaline Burst', 'Freeze', 'Poison', 'Wound', 'Zap'],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Paralize Removal',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 551616,
    nickname: 'King Naite Megazord',
    auctionEnd: 1626487200,
    currentBid: 7999,
    hasBeenBidded: false,
    outfitId: '128_0',
    serverId: 1,
    vocationId: 1,
    level: 504,
    skills: {
      magic: 10.92,
      club: 54.92,
      fist: 16.67,
      sword: 106.57,
      fishing: 10,
      axe: 52.16,
      distance: 12.95,
      shielding: 100.85,
    },
    items: [31633],
    charms: ['Dodge', 'Freeze', 'Wound', 'Zap'],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 551639,
    nickname: 'Stalowka',
    auctionEnd: 1626487200,
    currentBid: 1750,
    hasBeenBidded: false,
    outfitId: '132_3',
    serverId: 2,
    vocationId: 3,
    level: 333,
    skills: {
      magic: 95.68,
      club: 16.07,
      fist: 11.83,
      sword: 15.06,
      fishing: 10,
      axe: 12.05,
      distance: 16.31,
      shielding: 36.2,
    },
    items: [8864, 13996, 30399, 35563],
    charms: [],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 551650,
    nickname: 'Hermione Doomsday',
    auctionEnd: 1626487200,
    currentBid: 7000,
    hasBeenBidded: false,
    outfitId: '141_1',
    serverId: 3,
    vocationId: 1,
    level: 542,
    skills: {
      magic: 11.44,
      club: 21.17,
      fist: 18.4,
      sword: 55.1,
      fishing: 10.05,
      axe: 112.29,
      distance: 23.43,
      shielding: 105.3,
    },
    items: [],
    charms: ['Dodge', 'Freeze', 'Parry', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 551781,
    nickname: 'Mirenriel',
    auctionEnd: 1626487200,
    currentBid: 500,
    hasBeenBidded: true,
    outfitId: '128_0',
    serverId: 4,
    vocationId: 3,
    level: 93,
    skills: {
      magic: 38.86,
      club: 12.18,
      fist: 12.32,
      sword: 12.18,
      fishing: 10,
      axe: 12.18,
      distance: 12.19,
      shielding: 26.43,
    },
    items: [],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 552099,
    nickname: 'Tharollingston',
    auctionEnd: 1626487200,
    currentBid: 900,
    hasBeenBidded: false,
    outfitId: '130_1',
    serverId: 5,
    vocationId: 3,
    level: 286,
    skills: {
      magic: 89.89,
      club: 12.45,
      fist: 14.23,
      sword: 12.78,
      fishing: 10,
      axe: 12.45,
      distance: 12.53,
      shielding: 34.65,
    },
    items: [8864, 14087, 16175, 27457],
    charms: [],
    transfer: true,
    imbuements: [
      'Death Damage',
      'Death Protection',
      'Energy Damage',
      'Energy Protection',
      'Life Leech',
      'Speed',
    ],
    hasSoulwar: false,
  },
  {
    id: 552186,
    nickname: 'Smokzz',
    auctionEnd: 1626487200,
    currentBid: 2700,
    hasBeenBidded: false,
    outfitId: '1270_0',
    serverId: 6,
    vocationId: 2,
    level: 401,
    skills: {
      magic: 31.26,
      club: 26.15,
      fist: 26.01,
      sword: 31.06,
      fishing: 20.56,
      axe: 19.74,
      distance: 117.86,
      shielding: 103.83,
    },
    items: [10323, 16110, 16111, 22867],
    charms: ['Dodge', 'Freeze', 'Poison', 'Wound'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 553052,
    nickname: 'Dylozk',
    auctionEnd: 1626487200,
    currentBid: 3000,
    hasBeenBidded: true,
    outfitId: '130_1',
    serverId: 7,
    vocationId: 3,
    level: 344,
    skills: {
      magic: 93.81,
      club: 12.79,
      fist: 14.81,
      sword: 12.22,
      fishing: 10,
      axe: 11.73,
      distance: 18.04,
      shielding: 31.37,
    },
    items: [],
    charms: ['Wound', 'Zap'],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Life Leech',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 553112,
    nickname: 'Sakroth',
    auctionEnd: 1626487200,
    currentBid: 2500,
    hasBeenBidded: false,
    outfitId: '1245_3',
    serverId: 0,
    vocationId: 1,
    level: 388,
    skills: {
      magic: 10.7,
      club: 99.55,
      fist: 17.82,
      sword: 101.43,
      fishing: 33.79,
      axe: 59.23,
      distance: 13.54,
      shielding: 99.41,
    },
    items: [2974, 16110, 27651, 31614],
    charms: ['Dodge', 'Poison'],
    transfer: true,
    imbuements: [
      'Death Damage',
      'Death Protection',
      'Energy Damage',
      'Energy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Shield Skill',
      'Speed',
    ],
    hasSoulwar: false,
  },
  {
    id: 553114,
    nickname: 'Marginal do Manguebeat',
    auctionEnd: 1626487200,
    currentBid: 5500,
    hasBeenBidded: false,
    outfitId: '133_3',
    serverId: 1,
    vocationId: 1,
    level: 521,
    skills: {
      magic: 11.34,
      club: 60.13,
      fist: 18.45,
      sword: 106.79,
      fishing: 32.81,
      axe: 85.5,
      distance: 19.85,
      shielding: 101.04,
    },
    items: [9598, 27651, 31577, 34080],
    charms: ['Dodge', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 553257,
    nickname: 'King Veneh',
    auctionEnd: 1626487200,
    currentBid: 35000,
    hasBeenBidded: false,
    outfitId: '1331_3',
    serverId: 2,
    vocationId: 1,
    level: 837,
    skills: {
      magic: 12.36,
      club: 74.34,
      fist: 23.06,
      sword: 121.97,
      fishing: 13.62,
      axe: 58.81,
      distance: 26.13,
      shielding: 115.08,
    },
    items: [],
    charms: [
      'Cleanse',
      'Curse',
      'Dodge',
      'Freeze',
      'Parry',
      'Poison',
      'Wound',
      'Zap',
    ],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Paralize Removal',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 553335,
    nickname: 'Kakhonz',
    auctionEnd: 1626488100,
    currentBid: 2600,
    hasBeenBidded: true,
    outfitId: '137_0',
    serverId: 3,
    vocationId: 4,
    level: 471,
    skills: {
      magic: 101.34,
      club: 20.03,
      fist: 14.11,
      sword: 23.68,
      fishing: 11.55,
      axe: 12.65,
      distance: 20.28,
      shielding: 36.16,
    },
    items: [3388, 3414, 18339, 31578],
    charms: ['Gut'],
    transfer: true,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
  {
    id: 553338,
    nickname: 'Elderty goost',
    auctionEnd: 1626488100,
    currentBid: 4000,
    hasBeenBidded: false,
    outfitId: '129_0',
    serverId: 4,
    vocationId: 2,
    level: 497,
    skills: {
      magic: 34.03,
      club: 20.1,
      fist: 21.68,
      sword: 27.75,
      fishing: 10,
      axe: 10.76,
      distance: 113.86,
      shielding: 97.27,
    },
    items: [3253, 3414, 27565, 31617],
    charms: ['Dodge', 'Freeze', 'Parry'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 551971,
    nickname: 'Chong Wick',
    auctionEnd: 1626489000,
    currentBid: 14750,
    hasBeenBidded: false,
    outfitId: '152_3',
    serverId: 5,
    vocationId: 2,
    level: 644,
    skills: {
      magic: 36.2,
      club: 31.68,
      fist: 23.96,
      sword: 34.31,
      fishing: 28.96,
      axe: 13.59,
      distance: 122.42,
      shielding: 107.63,
    },
    items: [3031],
    charms: ['Cripple', 'Dodge', 'Freeze', 'Low Blow', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 547172,
    nickname: 'Xndcabrero',
    auctionEnd: 1626490800,
    currentBid: 89,
    hasBeenBidded: true,
    outfitId: '128_0',
    serverId: 6,
    vocationId: 4,
    level: 95,
    skills: {
      magic: 60.87,
      club: 12.88,
      fist: 10,
      sword: 12.88,
      fishing: 10,
      axe: 12.88,
      distance: 12.9,
      shielding: 30.32,
    },
    items: [3387, 12548],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 547202,
    nickname: 'Carlzera Toplinne',
    auctionEnd: 1626490800,
    currentBid: 5502,
    hasBeenBidded: false,
    outfitId: '129_0',
    serverId: 7,
    vocationId: 4,
    level: 352,
    skills: {
      magic: 93.26,
      club: 12.48,
      fist: 16.3,
      sword: 17.87,
      fishing: 10,
      axe: 12.49,
      distance: 13.05,
      shielding: 33.5,
    },
    items: [30400],
    charms: ['Freeze', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 548117,
    nickname: 'Barksz',
    auctionEnd: 1626490800,
    currentBid: 600,
    hasBeenBidded: false,
    outfitId: '134_3',
    serverId: 0,
    vocationId: 1,
    level: 198,
    skills: {
      magic: 9.3,
      club: 22.72,
      fist: 10.42,
      sword: 59.2,
      fishing: 10,
      axe: 110.93,
      distance: 13.51,
      shielding: 103.74,
    },
    items: [646, 7434],
    charms: ['Dodge'],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 551709,
    nickname: 'Thementalist',
    auctionEnd: 1626490800,
    currentBid: 11000,
    hasBeenBidded: false,
    outfitId: '152_3',
    serverId: 1,
    vocationId: 2,
    level: 601,
    skills: {
      magic: 34.64,
      club: 15.25,
      fist: 26.11,
      sword: 35.16,
      fishing: 21.37,
      axe: 13.17,
      distance: 120.33,
      shielding: 105.08,
    },
    items: [13994, 29417, 29427, 32617],
    charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 546494,
    nickname: 'räre nick',
    auctionEnd: 1626487200,
    currentBid: 10000,
    hasBeenBidded: true,
    outfitId: '1243_3',
    serverId: 0,
    vocationId: 2,
    level: 618,
    skills: {
      magic: 11.79,
      club: 38.84,
      fist: 21.62,
      sword: 42.97,
      fishing: 43.63,
      axe: 119.13,
      distance: 23.35,
      shielding: 112.49,
    },
    items: [9079, 31577, 31633, 32616],
    charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
] as PartialCharacterObject[]

export const serverData = [
  {
    serverId: 0,
    serverName: 'Adra',
    serverLocation: {
      string: 'EU',
      type: 0,
    },
    pvpType: {
      string: 'Open',
      type: 1,
    },
    battleye: true,
    experimental: false,
  },
  {
    serverId: 1,
    serverName: 'Antica',
    serverLocation: {
      string: 'EU',
      type: 0,
    },
    pvpType: {
      string: 'Open',
      type: 1,
    },
    battleye: false,
    experimental: false,
  },
  {
    serverId: 2,
    serverName: 'Assombra',
    serverLocation: {
      string: 'BR',
      type: 2,
    },
    pvpType: {
      string: 'Retro Hardcore',
      type: 4,
    },
    battleye: true,
    experimental: false,
  },
  {
    serverId: 3,
    serverName: 'Astera',
    serverLocation: {
      string: 'NA',
      type: 1,
    },
    pvpType: {
      string: 'Optional',
      type: 0,
    },
    battleye: false,
    experimental: false,
  },
  {
    serverId: 4,
    serverName: 'Belluma',
    serverLocation: {
      string: 'EU',
      type: 0,
    },
    pvpType: {
      string: 'Open',
      type: 1,
    },
    battleye: true,
    experimental: false,
  },
  {
    serverId: 5,
    serverName: 'Belobra',
    serverLocation: {
      string: 'BR',
      type: 2,
    },
    pvpType: {
      string: 'Optional',
      type: 0,
    },
    battleye: false,
    experimental: false,
  },
  {
    serverId: 6,
    serverName: 'Bona',
    serverLocation: {
      string: 'EU',
      type: 0,
    },
    pvpType: {
      string: 'Optional',
      type: 0,
    },
    battleye: false,
    experimental: false,
  },
  {
    serverId: 7,
    serverName: 'Calmera',
    serverLocation: {
      string: 'NA',
      type: 1,
    },
    pvpType: {
      string: 'Optional',
      type: 0,
    },
    battleye: false,
    experimental: false,
  },
] as ServerObject[]

export const itemData = {
  "Chayenne's Magical Key": [551661],
  'Pair of Soulstalkers': [548277],
  'Pair of Soulwalkers': [553765, 553418],
  Soulbiter: [550702, 553765, 551286],
  Soulbleeder: [548277],
  Soulcrusher: [554187, 552265, 534926],
  Soulhexer: [550878, 546836, 554154, 544736],
  Soulmaimer: [550235, 554187, 549515, 552265],
  Soulpiercer: [548277],
  Soulshanks: [554093, 552149],
  Soulshell: [548277],
  Soulshredder: [551512],
  Soulshroud: [546836, 553629],
  Soulstrider: [546836, 554154, 553629],
  Soultainter: [550726, 552149],
} as RareItemData

export const completeCharData = buildCharacterData(charBuildedData, serverData)

export const filterTestA = {
  nicknameFilter: '',
  vocation: new Set([1]),
  pvp: new Set([]),
  battleye: new Set([]),
  location: new Set([]),
  serverSet: new Set([]),
  minLevel: 600,
  maxLevel: 2000,
  minSkill: 10,
  skillKey: new Set([]),
  itemSet: new Set([]),
  fav: false,
  rareNick: false,
  soulwarFilter: false,
  imbuementsSet: new Set([]),
} as FilterState

export const filterResultA = [
  {
    id: 546494,
    nickname: 'Delageez Shelby',
    auctionEnd: 1626487200,
    currentBid: 10000,
    hasBeenBidded: true,
    outfitId: '1243_3',
    serverId: 0,
    vocationId: 1,
    level: 618,
    skills: {
      magic: 11.79,
      club: 38.84,
      fist: 21.62,
      sword: 42.97,
      fishing: 43.63,
      axe: 119.13,
      distance: 23.35,
      shielding: 112.49,
    },
    items: [9079, 31577, 31633, 32616],
    charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
    serverData: {
      serverId: 0,
      serverName: 'Adra',
      serverLocation: { string: 'EU', type: 0 },
      pvpType: {
        string: 'Open',
        type: 1,
      },
      battleye: true,
      experimental: false,
    },
  },
  {
    id: 553257,
    nickname: 'King Veneh',
    auctionEnd: 1626487200,
    currentBid: 35000,
    hasBeenBidded: false,
    outfitId: '1331_3',
    serverId: 2,
    vocationId: 1,
    level: 837,
    skills: {
      magic: 12.36,
      club: 74.34,
      fist: 23.06,
      sword: 121.97,
      fishing: 13.62,
      axe: 58.81,
      distance: 26.13,
      shielding: 115.08,
    },
    items: [],
    charms: [
      'Cleanse',
      'Curse',
      'Dodge',
      'Freeze',
      'Parry',
      'Poison',
      'Wound',
      'Zap',
    ],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Paralize Removal',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
    serverData: {
      serverId: 2,
      serverName: 'Assombra',
      serverLocation: { string: 'BR', type: 2 },
      pvpType: { string: 'Retro Hardcore', type: 4 },
      battleye: true,
      experimental: false,
    },
  },
] as CharacterObject[]

export const initialFilter = {
  nicknameFilter: '',
  vocation: new Set([]),
  pvp: new Set([]),
  battleye: new Set([]),
  location: new Set([]),
  serverSet: new Set([]),
  minLevel: 8,
  maxLevel: 2000,
  minSkill: 10,
  skillKey: new Set([]),
  itemSet: new Set([]),
  fav: false,
  rareNick: false,
  soulwarFilter: false,
  imbuementsSet: new Set([]),
} as FilterState
