import Head from 'next/head'
import { Main } from 'templates'
import { BazaarHistory as BazaarHistoryGrid } from 'modules/BazaarAuctions'

export default function BazaarHistory(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Exevo Pan - Bazaar History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <BazaarHistoryGrid />
      </Main>
    </div>
  )
}
