export default [
  'Aug. Great Death Beam (+8% Critical Extra Damage)',
  'Revelation Mastery (+150 Gift of Life)',
  'Revelation Mastery (+150 Avatar of Storm)',
  'Aug. Energy Wave (Damage Increase)',
  'Aug. Great Fire Wave (+8% Critical Extra Damage)',
  'Aug. Avatar of Storm (-300s Cooldown)',
  'Aug. Great Death Beam (Damage Increase)',
  '+0.25% Dodge',
  'Revelation Mastery (+150 Beam Mastery)',
  'Aug. Energy Wave (-1s Cooldown)',
  "Aug. Hell's Core (Damage Increase)",
  'Aug. Ultimate Healing (Healing Increase)',
  "Aug. Hell's Core (+8% Critical Extra Damage)",
  'Aug. Great Fire Wave (Damage Increase)',
  'Aug. Great Energy Beam (+8% Critical Extra Damage)',
  'Aug. Energy Wave (+8% Critical Extra Damage)',
  'Revelation Mastery (+150 Drain Body)',
  '+1.2% Life Leech',
  'Aug. Rage of the Skies (+8% Critical Extra Damage)',
  'Aug. Great Energy Beam (Damage Increase)',
  'Aug. Rage of the Skies (Damage Increase)',
  '+0.4% Mana Leech',
]
