import { memo } from 'react'
import clsx from 'clsx'
import CharacterCard from 'components/CharacterCard'
import styles from './styles.module.css'

const GoodAuction = () => (
  <CharacterCard
    className={clsx('pointer-events-none mx-auto max-w-[360px]', styles.card)}
    highlighted
    characterData={{
      id: 0,
      nickname: 'Your Super Character',
      auctionEnd: 1872167600,
      currentBid: 130000,
      hasBeenBidded: true,
      outfitId: '1210_3',
      serverId: 49,
      vocationId: 1,
      sex: false,
      level: 867,
      achievementPoints: 944,
      bossPoints: 2136,
      tcInvested: 23625,
      tags: [
        'manyStoreCosmetics',
        'rareMounts',
        'rareOutfits',
        'secondaryEkSkill',
      ],
      skills: {
        magic: 12.23,
        club: 129.37,
        fist: 13,
        sword: 32.41,
        fishing: 10,
        axe: 117.31,
        distance: 23.55,
        shielding: 103.61,
      },
      items: [34085, 28720, 28715, 34097],
      transfer: true,
      imbuements: [
        'Axe Skill',
        'Capacity',
        'Club Skill',
        'Critical Hit',
        'Death Damage',
        'Death Protection',
        'Distance Skill',
        'Earth Damage',
        'Earth Protection',
        'Energy Damage',
        'Energy Protection',
        'Fire Damage',
        'Fire Protection',
        'Holy Protection',
        'Ice Damage',
        'Ice Protection',
        'Life Leech',
        'Magic Level',
        'Mana Leech',
        'Paralize Removal',
        'Shield Skill',
        'Speed',
        'Sword Skill',
      ],
      quests: [
        'The Order of the Cobra',
        'Feaster of Souls',
        'Dangerous Depths (Warzone 4)',
        'Cults of Tibia',
        'Grimvale',
        'The Dream Courts',
        'Dangerous Depths (Warzone 6)',
        "Bigfoot's Burden (Free boss access)",
        'Dangerous Depths (Warzone 5)',
        'Barbarian Test',
        "Bigfoot's Burden (Rank IV)",
        'The Secret Library',
        "Lion's Rock",
        'The Order of the Lion',
        'Asura Palace',
        'The Order of the Falcon',
        'The Curse Spreads',
        'Rathleton (Citzen)',
        'The Travelling Trader (Rashid)',
        'Kilmaresh',
        'Blood Brothers',
        'Dark Trails',
        "Ferumbras' Ascendant",
        'Heart of Destruction',
        'Hero of Rathleton',
        'Primal Ordeal',
        'Shadows of Yalahar',
        'Soul War',
        'The Ape City',
        'The Djinn War (green)',
        'The Ice Islands',
        'The Inquisition',
        'The New Frontier',
        'The Pits of Inferno',
        'The Postman Missions',
        'The Shattered Isles',
        'The Thieves Guild',
        'Twenty Miles Beneath the Sea',
        'Wrath of the Emperor',
      ],
      greaterGems: [],
      gems: { lesser: 0, greater: 0, regular: 0 },
      storeItems: [],
      outfits: [],
      storeOutfits: [],
      mounts: [],
      storeMounts: [],
      rareAchievements: [],
      hirelings: {
        count: 0,
        jobs: 0,
        outfits: 0,
      },
      huntingSlot: true,
      preySlot: true,
      charmInfo: {
        total: 3354,
        expansion: true,
      },
      serverData: {
        serverId: 49,
        serverName: 'Nossobra',
        serverLocation: {
          string: 'BR',
          type: 2,
        },
        pvpType: {
          string: 'Retro Open',
          type: 2,
        },
        battleye: true,
        experimental: false,
      },
      animusMasteries: 0,
    }}
  />
)

export default memo(GoodAuction)
