export const mockedHashData = [123, 456, 789]

export const oldAuction = {
  id: 546494,
  nickname: 'Delageez Shelby',
  auctionEnd: 1000000000,
  currentBid: 10000,
  hasBeenBidded: true,
  outfitId: '1243_3',
  serverId: 66,
  vocationId: 1,
  level: 618,
  skills: {
    magic: 11.79,
    club: 38.84,
    fist: 21.62,
    sword: 42.97,
    fishing: 43.63,
    axe: 119.13,
    distance: 23.35,
    shielding: 112.49,
  },
  items: [9079, 31577, 31633, 32616],
  charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
  transfer: false,
  imbuements: [
    'Axe Skill',
    'Capacity',
    'Club Skill',
    'Critical Hit',
    'Death Damage',
    'Death Protection',
    'Distance Skill',
    'Earth Damage',
    'Earth Protection',
    'Energy Damage',
    'Energy Protection',
    'Fire Damage',
    'Fire Protection',
    'Holy Protection',
    'Ice Damage',
    'Ice Protection',
    'Life Leech',
    'Magic Level',
    'Mana Leech',
    'Shield Skill',
    'Speed',
    'Sword Skill',
  ],
  hasSoulwar: true,
} as PartialCharacterObject

export const normalAuction = {
  id: 548069,
  nickname: 'Ganluca',
  auctionEnd: 1626487200,
  currentBid: 5011,
  hasBeenBidded: true,
  outfitId: '146_3',
  serverId: 31,
  vocationId: 1,
  level: 502,
  skills: {
    magic: 11.09,
    club: 44.25,
    fist: 14.15,
    sword: 55.19,
    fishing: 10.15,
    axe: 114.66,
    distance: 26.95,
    shielding: 107.27,
  },
  items: [16110, 16161, 21892, 31633],
  charms: ['Dodge', 'Freeze', 'Zap'],
  transfer: false,
  imbuements: [
    'Axe Skill',
    'Club Skill',
    'Critical Hit',
    'Death Damage',
    'Death Protection',
    'Earth Damage',
    'Earth Protection',
    'Energy Damage',
    'Energy Protection',
    'Fire Damage',
    'Fire Protection',
    'Life Leech',
    'Magic Level',
    'Mana Leech',
    'Speed',
    'Sword Skill',
  ],
  hasSoulwar: false,
} as PartialCharacterObject

export const futureAuction = {
  id: 550233,
  nickname: 'Stonurath Thel',
  auctionEnd: 9999999999,
  currentBid: 253,
  hasBeenBidded: true,
  outfitId: '131_0',
  serverId: 83,
  vocationId: 1,
  level: 8,
  skills: {
    magic: 2.35,
    club: 101.06,
    fist: 10,
    sword: 14,
    fishing: 10,
    axe: 14,
    distance: 13.64,
    shielding: 93.79,
  },
  items: [],
  charms: [],
  transfer: true,
  imbuements: [],
  hasSoulwar: false,
} as PartialCharacterObject

export const sortedAuctions = [
  {
    id: 550233,
    nickname: 'Stonurath Thel',
    auctionEnd: 9999999999,
    currentBid: 253,
    hasBeenBidded: true,
    outfitId: '131_0',
    serverId: 83,
    vocationId: 1,
    level: 8,
    skills: {
      magic: 2.35,
      club: 101.06,
      fist: 10,
      sword: 14,
      fishing: 10,
      axe: 14,
      distance: 13.64,
      shielding: 93.79,
    },
    items: [],
    charms: [],
    transfer: true,
    imbuements: [],
    hasSoulwar: false,
  },
  {
    id: 548069,
    nickname: 'Ganluca',
    auctionEnd: 1626487200,
    currentBid: 5011,
    hasBeenBidded: true,
    outfitId: '146_3',
    serverId: 31,
    vocationId: 1,
    level: 502,
    skills: {
      magic: 11.09,
      club: 44.25,
      fist: 14.15,
      sword: 55.19,
      fishing: 10.15,
      axe: 114.66,
      distance: 26.95,
      shielding: 107.27,
    },
    items: [16110, 16161, 21892, 31633],
    charms: ['Dodge', 'Freeze', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: false,
  },
  {
    id: 546494,
    nickname: 'Delageez Shelby',
    auctionEnd: 1000000000,
    currentBid: 10000,
    hasBeenBidded: true,
    outfitId: '1243_3',
    serverId: 66,
    vocationId: 1,
    level: 618,
    skills: {
      magic: 11.79,
      club: 38.84,
      fist: 21.62,
      sword: 42.97,
      fishing: 43.63,
      axe: 119.13,
      distance: 23.35,
      shielding: 112.49,
    },
    items: [9079, 31577, 31633, 32616],
    charms: ['Dodge', 'Freeze', 'Parry', 'Poison', 'Wound', 'Zap'],
    transfer: false,
    imbuements: [
      'Axe Skill',
      'Capacity',
      'Club Skill',
      'Critical Hit',
      'Death Damage',
      'Death Protection',
      'Distance Skill',
      'Earth Damage',
      'Earth Protection',
      'Energy Damage',
      'Energy Protection',
      'Fire Damage',
      'Fire Protection',
      'Holy Protection',
      'Ice Damage',
      'Ice Protection',
      'Life Leech',
      'Magic Level',
      'Mana Leech',
      'Shield Skill',
      'Speed',
      'Sword Skill',
    ],
    hasSoulwar: true,
  },
] as PartialCharacterObject[]
