export const itemList: string[] = [
  'Amazon Armor',
  'Amazon Helmet',
  'Amazon Shield',
  'Ball Gown',
  'Blessed Shield',
  'Blue Sphere',
  'Blue Tome',
  /* 'Broken Amulet', */
  'Bronze Necklace',
  /* 'Bunnyslippers', */
  "Chayenne's Magical Key",
  'Crackling Egg',
  'Dark Trinity Mace',
  'Elemental Spikes',
  'Eye of the Storm',
  "Ferumbras' Hat",
  'Gamemaster Doll',
  'Golden Crown',
  'Golden Helmet',
  /* 'Golden Rune', */
  'Green Tome',
  'Grey Tome',
  'Hammer of Prophecy',
  'Horned Helmet',
  'Key to Knowledge',
  'Magic Longsword',
  'Menacing Egg',
  'Mysterious Scroll',
  'Pair of Soulstalkers',
  'Pair of Soulwalkers',
  'Rose Shield',
  'Shield of Honour',
  'Solar Axe',
  'Soulbastion',
  'Soulbiter',
  'Soulbleeder',
  'Soulcrusher',
  'Soulcutter',
  /* 'Souleater', */
  'Soulhexer',
  'Soulmaimer',
  'Soulmantle',
  'Soulpiercer',
  'Soulshanks',
  'Soulshell',
  'Soulshredder',
  'Soulshroud',
  'Soulstrider',
  'Soultainter',
  'Spectral Saddle',
  'The Devileye',
  'The Epiphany',
  'Thunder Hammer',
  'Warlord Sword',
  /* 'Winged Helmet', */
  /* 'Yellow Rose' */
]
