export const itemList: string[] = [
  'Alicorn Headguard',
  'Alicorn Quiver',
  'Alicorn Ring',
  'Amazon Armor',
  'Amazon Helmet',
  'Amazon Shield',
  'Arboreal Crown',
  'Arboreal Ring',
  'Arboreal Tome',
  'Arcanomancer Folio',
  'Arcanomancer Sigil',
  'Ball Gown',
  'Blessed Shield',
  'Blue Sphere',
  'Blue Tome',
  /* 'Broken Amulet', */
  'Bracelet of Strengthening',
  'Bronze Necklace',
  /* 'Bunnyslippers', */
  "Chayenne's Magical Key",
  'Crackling Egg',
  "Dark Lord's Cape",
  'Dark Trinity Mace',
  'Eldritch Claymore',
  'Eldritch Hood',
  'Eldritch Quiver',
  'Eldritch Shield',
  'Eldritch Tome',
  'Elemental Spikes',
  'Eye of the Storm',
  "Ferumbras' Hat",
  'Gamemaster Doll',
  'Gilded Eldritch Greataxe',
  'Golden Crown',
  'Golden Helmet',
  /* 'Golden Rune', */
  'Green Demon Armor',
  'Green Demon Helmet',
  'Green Demon Slippers',
  'Green Tome',
  'Grey Tome',
  'Hammer of Prophecy',
  'Horned Helmet',
  'Key to Knowledge',
  'Magic Longsword',
  'Menacing Egg',
  "Morshabaal's Mask",
  'Mysterious Scroll',
  'Pair of Soulstalkers',
  'Pair of Soulwalkers',
  'Robe of the Ice Queen',
  'Rose Shield',
  'Shield of Honour',
  'Solar Axe',
  'Soulbastion',
  'Soulbiter',
  'Soulbleeder',
  'Soulcrusher',
  'Soulcutter',
  /* 'Souleater', */
  'Soulhexer',
  'Soulmaimer',
  'Soulmantle',
  'Soulpiercer',
  'Soulshanks',
  'Soulshell',
  'Soulshredder',
  'Soulshroud',
  'Soulstrider',
  'Soultainter',
  'Spectral Saddle',
  'Spiritthorn Armor',
  'Spiritthorn Helmet',
  'Spiritthorn Ring',
  'The Devileye',
  'The Epiphany',
  'Thunder Hammer',
  'Warlord Sword',
  /* 'Winged Helmet', */
  /* 'Yellow Rose' */
]
